version: '3.8'
services:
  encore:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - .docker/entrypoint.sh:/docker/entrypoint.sh
    ports:
      - "5173:5173"
      - "4173:4173"