version: '3.8'
services:
  encore:
    image: node:21-bookworm
    volumes:
      - .:/app
      - .docker/entrypoint.sh:/app/.docker/entrypoint.sh [ro]
    working_dir: /app
    ports:
      - "5173:5173"
      - "4173:4173"
    entrypoint: ".docker/entrypoint.sh"